name: Discord Notif
on: [push, pull_request]
  

permissions:
  contents: read
  security-events: write

jobs:
    # Post a message to the ITAS Discord channel with pipeline updates.
    Discord-Begin:
      runs-on: ubuntu-latest
      steps:
      - name: Discord Notification start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{github.repository}}
          avatar-url: https://thumbs.dreamstime.com/b/smoking-fish-11296061.jpg
          embed-title: "Security Pipeline jobs are starting..."
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
