# Name of this GitHub Actions workflow.
name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/securityLab.yml

permissions:
  contents: read
  security-events: write

jobs:
    semgrep:
      name: semgrep/ci
      runs-on: ubuntu-latest
      needs: [trufflehog]
  
      container:
        image: semgrep/semgrep
      if: (github.actor != 'dependabot[bot]')
  
      steps:
        - uses: actions/checkout@v4
        - run: semgrep ci --sarif > semgrep.sarif
          env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        - name: Upload a semgrep sarif
          uses: actions/upload-artifact@v4.6.1
          with:
            name: semgrep.sarif
            path: semgrep.sarif
            
    snyk:
      runs-on: ubuntu-latest
      needs: [trufflehog]
      steps:
      - uses: actions/checkout@v2
      - name: Build a Docker image

        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_APP_TOKEN }}
        with:
          image: shatch503/itas276-lab2:latest
          args: --file=Dockerfile
      - name: Upload result
        uses: actions/upload-artifact@v4.6.1
        with:
            name: snyk.sarif
            path: snyk.sarif
            
    trufflehog:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified


   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
